mkdir -p .github/workflows
cat > .github/workflows/daily-update.yml << 'EOF'
name: Daily Nifty500 Update

# Cron in UTC; for 02:00 IST daily use 20:30 UTC prev. day
on:
  schedule:
    - cron: '30 20 * * *' 

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Firebase key JSON
        env:
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
        run: |
          echo "$FIREBASE_KEY_JSON" > serviceAccountKey.json

      - name: Run update script
        run: |
          python update_firebase.py
EOF
