name: Daily Nifty500 Update

on:
  schedule:
    - cron: '30 20 * * *'  # Runs daily at 2:00 AM IST (20:30 UTC prev. day)
  workflow_dispatch:        # Allow manual trigger from GitHub Actions UI

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Firebase key JSON
        env:
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
        run: |
          echo "$FIREBASE_KEY_JSON" > serviceAccountKey.json

      - name: Run update script
        run: |
          python update_firebase.py

      - name: Commit and push changes (if any)
        run: |
          git config --local user.email "saikoduri111@gmail.com"
          git config --local user.name "Sai Kumar"
          git add .
          git diff --cached --quiet || git commit -m "Automated daily update"
          git push
